openapi: 3.0.3
info:
  title: Stress-ng Test API
  description: API for running stress-ng tests
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /login:
    post:
      summary: Login to the application
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "302":
          description: Redirect on successful login
        "200":
          description: Invalid username or password
          content:
            text/html:
              schema:
                type: string
  /logout:
    get:
      summary: Logout from the application
      responses:
        "302":
          description: Redirect to the login page

  /home:
    get:
      summary: Get the home page of the application
      responses:
        "200":
          description: Successful response
          content:
            text/html:
              schema:
                type: string

  /stress_ng:
    get:
      summary: Get the stress-ng page
      responses:
        "200":
          description: Successful response
          content:
            text/html:
              schema:
                type: string

  /local_stress_test/stress_cpu:
    post:
      summary: Run CPU stress test locally
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                cpu_workers:
                  type: integer
                  default: 1
                stress_time:
                  type: integer
                  default: 60
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /local_stress_test/stress_memory:
    post:
      summary: Run memory stress test locally
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                memory_workers:
                  type: integer
                  default: 1
                stress_time:
                  type: integer
                  default: 60
                vm_bytes:
                  type: string
                  default: '512M'
                vm_stressors:
                  type: integer
                  default: 1
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /local_stress_test/stress_io:
    post:
      summary: Run I/O stress test locally
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                io_workers:
                  type: integer
                  default: 1
                stress_time:
                  type: integer
                  default: 60
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /remote_server_stress-test/re_stress_cpu:
    post:
      summary: Run CPU stress test on a remote server
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                remote_server_name:
                  type: string
                remote_cpu_workers:
                  type: integer
                  default: 1
                remote_stresstime:
                  type: integer
                  default: 60
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /remote_server_stress-test/re_stress_memory:
    post:
      summary: Run memory stress test on a remote server
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                remote_server_name:
                  type: string
                memory_workers:
                  type: integer
                  default: 1
                remote_stresstime:
                  type: integer
                  default: 60
                remote_vmbytes:
                  type: string
                  default: '512M'
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /remote_server_stress-test/re_stress_io:
    post:
      summary: Run I/O stress test on a remote server
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                remote_server_name:
                  type: string
                remote_ioworkers:
                  type: integer
                  default: 1
                remote_stresstime:
                  type: integer
                  default: 60
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string

  /swagger:
    get:
      summary: Get the Swagger UI page
      responses:
        "200":
          description: Successful response
          content:
            text/html:
              schema:
                type: string
